version: '3.8'

services:

  nest-back:
    build: .
    volumes:
      - .:/nest-back
    container_name: nest-back
    hostname: nest-back
    depends_on:
      - nest-db
    ports:
      - '3001:3001'
    expose:
      - '3001'
    restart: unless-stopped
    env_file: ./.env
    networks:
      - nest

  nest-db:
    image: postgres:15.2-alpine3.17
    container_name: nest-db
    hostname: nest-db
    environment:
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - nest-db:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5432:5432'
    restart: always
    networks:
      - nest

  nest-pgadmin:
    container_name: nest-pgadmin
    hostname: nest-pgadmin
    volumes:
      - nest-pgadmin:/var/lib/pgadmin
    depends_on:
      - nest-db
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    expose:
      - '80'
    ports:
      - '5051:80'
    restart: always
    networks:
      - nest
    logging:
      driver: none

networks:
  nest:
    external: true

volumes:
  nest-db:
    external: true
  nest-pgadmin:
    external: true